import JSZip from "jszip";
import { DOCUMENT_VERSION, flattenLayerLinks, type ArtMakerDocument, type SourceAsset } from "./types";

export function migrateDocument(input: unknown): ArtMakerDocument { const raw=input as Record<string,unknown>; if(raw.format!=="artmaker"||!raw.version||Number(raw.version)>DOCUMENT_VERSION) throw new Error("Unsupported ArtMaker project version"); const document=structuredClone(raw) as unknown as ArtMakerDocument; const migrateLayers=(layers:typeof document.layers)=>{for(const layer of layers){layer.effects=layer.effects.map((effect)=>{const legacy=effect as unknown as {id:string;type:string;enabled:boolean;params:Record<string,number|string|boolean>};if(Number(raw.version)===1&&legacy.type==="colorize")return{id:legacy.id,type:"replaceColor",version:2,enabled:legacy.enabled,params:{sourceColor:"#000000",tolerance:100,softness:0,...legacy.params}};if(Number(raw.version)===1&&legacy.type==="gradient")return{id:legacy.id,type:"gradientReplaceColor",version:2,enabled:legacy.enabled,params:{sourceColor:"#000000",tolerance:100,softness:0,...legacy.params}};if(legacy.type==="halftone")return{id:legacy.id,type:"halftone",version:2,enabled:legacy.enabled,params:{dot:Math.max(1,Number(legacy.params.dot??4)),spacingX:Math.max(1,Number(legacy.params.spacingX??1)),spacingY:Math.max(1,Number(legacy.params.spacingY??1)),stagger:Boolean(legacy.params.stagger)}};return{...legacy,version:2} as typeof effect;});if(layer.children)migrateLayers(layer.children)}};migrateLayers(document.layers);flattenLayerLinks(document.layers);document.version=DOCUMENT_VERSION;return document; }

const DB = "artmaker", STORE = "autosave";
const openDb = () => new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open(DB, 1); request.onupgradeneeded = () => request.result.createObjectStore(STORE); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
export async function saveAutosave(document: ArtMakerDocument, assets: Map<string, SourceAsset>) { const db = await openDb(); const data = { document, assets: [...assets.values()] }; await new Promise<void>((resolve,reject)=>{ const tx=db.transaction(STORE,"readwrite"); tx.objectStore(STORE).put(data,"current"); tx.oncomplete=()=>resolve(); tx.onerror=()=>reject(tx.error); }); db.close(); }
export async function loadAutosave(): Promise<{document:ArtMakerDocument;assets:SourceAsset[]}|null> { const db=await openDb(); const result=await new Promise<unknown>((resolve,reject)=>{ const req=db.transaction(STORE).objectStore(STORE).get("current"); req.onsuccess=()=>resolve(req.result); req.onerror=()=>reject(req.error); }); db.close(); if(!result)return null;const saved=result as {document:unknown;assets:SourceAsset[]};return{document:migrateDocument(saved.document),assets:saved.assets}; }

export function prepareExportDocument(document: ArtMakerDocument) {
  const clean = structuredClone(document);
  for (const layer of clean.layers) {
    if (!layer.linkSourceId) continue;
    delete layer.bitmap;
    delete layer.assetId;
  }
  return clean;
}
export async function exportProject(document: ArtMakerDocument, assets: Map<string, SourceAsset>) { const zip=new JSZip(); zip.file("project.json",JSON.stringify(prepareExportDocument(document),null,2)); for(const asset of assets.values()) zip.file(`assets/${asset.id}`,asset.bytes); zip.file("manifest.json",JSON.stringify({format:"artmaker",version:DOCUMENT_VERSION,createdBy:"ArtMaker"})); return zip.generateAsync({type:"blob",compression:"DEFLATE"}); }
export async function importProject(file: Blob): Promise<{document:ArtMakerDocument;assets:SourceAsset[]}> { const zip=await JSZip.loadAsync(file), entry=zip.file("project.json"); if(!entry) throw new Error("Invalid ArtMaker project: project.json is missing"); const document=migrateDocument(JSON.parse(await entry.async("text"))); const assets:SourceAsset[]=[]; for(const layer of document.layers){ if(!layer.assetId) continue; const data=zip.file(`assets/${layer.assetId}`); if(!data) throw new Error(`Missing source asset: ${layer.assetId}`); const bytes=await data.async("blob"); assets.push({id:layer.assetId,name:layer.name,mime:bytes.type||"application/octet-stream",width:0,height:0,checksum:"",bytes}); } return {document,assets}; }
export function download(blob: Blob, filename: string) { const url=URL.createObjectURL(blob), a=document.createElement("a"); a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
