import JSZip from "jszip";
import type { ArtMakerDocument, SourceAsset } from "./types";

const DB = "artmaker", STORE = "autosave";
const openDb = () => new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open(DB, 1); request.onupgradeneeded = () => request.result.createObjectStore(STORE); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
export async function saveAutosave(document: ArtMakerDocument, assets: Map<string, SourceAsset>) { const db = await openDb(); const data = { document, assets: [...assets.values()] }; await new Promise<void>((resolve,reject)=>{ const tx=db.transaction(STORE,"readwrite"); tx.objectStore(STORE).put(data,"current"); tx.oncomplete=()=>resolve(); tx.onerror=()=>reject(tx.error); }); db.close(); }
export async function loadAutosave(): Promise<{document:ArtMakerDocument;assets:SourceAsset[]}|null> { const db=await openDb(); const result=await new Promise<unknown>((resolve,reject)=>{ const req=db.transaction(STORE).objectStore(STORE).get("current"); req.onsuccess=()=>resolve(req.result); req.onerror=()=>reject(req.error); }); db.close(); return result as {document:ArtMakerDocument;assets:SourceAsset[]}|null; }

export async function exportProject(document: ArtMakerDocument, assets: Map<string, SourceAsset>) { const zip=new JSZip(); const clean=structuredClone(document); zip.file("project.json",JSON.stringify(clean,null,2)); for(const asset of assets.values()) zip.file(`assets/${asset.id}`,asset.bytes); zip.file("manifest.json",JSON.stringify({format:"artmaker",version:1,createdBy:"ArtMaker"})); return zip.generateAsync({type:"blob",compression:"DEFLATE"}); }
export async function importProject(file: Blob): Promise<{document:ArtMakerDocument;assets:SourceAsset[]}> { const zip=await JSZip.loadAsync(file), entry=zip.file("project.json"); if(!entry) throw new Error("Invalid ArtMaker project: project.json is missing"); const document=JSON.parse(await entry.async("text")) as ArtMakerDocument; if(document.format!=="artmaker"||document.version!==1) throw new Error("Unsupported ArtMaker project version"); const assets:SourceAsset[]=[]; for(const layer of document.layers){ if(!layer.assetId) continue; const data=zip.file(`assets/${layer.assetId}`); if(!data) throw new Error(`Missing source asset: ${layer.assetId}`); const bytes=await data.async("blob"); assets.push({id:layer.assetId,name:layer.name,mime:bytes.type||"application/octet-stream",width:0,height:0,checksum:"",bytes}); } return {document,assets}; }
export function download(blob: Blob, filename: string) { const url=URL.createObjectURL(blob), a=document.createElement("a"); a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
