<script lang="ts">
  import { onMount, tick } from "svelte";
  import { createEffect, effectRegistry, processPixels } from "../lib/effects";
  import { documentPixels, newDocument, newLayer, toPixels, uid, type ArtLayer, type ArtMakerDocument, type EffectType, type SourceAsset, type Tool } from "../lib/types";
  import { download, exportProject, importProject, loadAutosave, saveAutosave } from "../lib/project";

  let locale: "zh-CN"|"en" = "zh-CN", doc: ArtMakerDocument = newDocument(locale), assets = new Map<string,SourceAsset>();
  let canvas: HTMLCanvasElement, stage: HTMLDivElement, fileInput: HTMLInputElement, projectInput: HTMLInputElement;
  let tool: Tool = "brush", color="#161616", size=18, zoom=1, drawing=false, start={x:0,y:0}, snapshot:ImageData|null=null;
  let panning=false, panStart={x:0,y:0,left:0,top:0}, cursor={x:0,y:0,visible:false};
  const layerBuffers=new Map<string,HTMLCanvasElement>();
  let status="", showSettings=false, showEffects=false, history:string[] = [], future:string[]=[];
  let settingsOriginal:ArtMakerDocument["spec"]|null=null;
  const zh:Record<string,string>={new:"新建",open:"打开",save:"保存项目",export:"导出 PNG",undo:"撤销",redo:"重做",import:"导入图片",settings:"文档设置",layers:"图层",effects:"特效",addLayer:"新建图层",addText:"文字",duplicate:"复制",remove:"删除",width:"成品宽",height:"成品高",dpi:"DPI",bleed:"出血",safe:"安全区",pixel:"画布像素",opacity:"不透明度",blend:"混合",empty:"选择图层后添加效果",restore:"已恢复自动保存",saved:"已自动保存",lang:"EN",theme:"主题"};
  const en:Record<string,string>={new:"New",open:"Open",save:"Save project",export:"Export PNG",undo:"Undo",redo:"Redo",import:"Import image",settings:"Document settings",layers:"Layers",effects:"Effects",addLayer:"New layer",addText:"Text",duplicate:"Duplicate",remove:"Delete",width:"Trim width",height:"Trim height",dpi:"DPI",bleed:"Bleed",safe:"Safe area",pixel:"Canvas pixels",opacity:"Opacity",blend:"Blend",empty:"Select a layer to add effects",restore:"Autosave restored",saved:"Autosaved",lang:"中文",theme:"Theme"};
  const t=(key:string)=>(locale==="zh-CN"?zh:en)[key]??key;
  const tools:{id:Tool;icon:string;zh:string;en:string}[]=[{id:"select",icon:"↖",zh:"选择",en:"Select"},{id:"brush",icon:"●",zh:"画笔",en:"Brush"},{id:"eraser",icon:"◇",zh:"橡皮",en:"Eraser"},{id:"line",icon:"╱",zh:"直线",en:"Line"},{id:"rect",icon:"□",zh:"矩形",en:"Rectangle"},{id:"ellipse",icon:"○",zh:"椭圆",en:"Ellipse"},{id:"fill",icon:"▰",zh:"填充",en:"Fill"},{id:"eyedropper",icon:"◉",zh:"吸管",en:"Eyedropper"}];
  $: px=documentPixels(doc.spec); $: safePx=toPixels(doc.spec.safeMargin,doc.spec.unit,doc.spec.dpi); $: active=doc.layers.find(l=>l.id===doc.activeLayerId); $: canvasStyle=`width:${px.width*zoom}px;height:${px.height*zoom}px`;

  function blankBuffer(){const c=document.createElement("canvas");c.width=px.width;c.height=px.height;return c;}
  function bufferFor(layer:ArtLayer){let b=layerBuffers.get(layer.id);if(!b){b=blankBuffer();layerBuffers.set(layer.id,b)}return b;}
  async function hydrateLayers(){layerBuffers.clear();await Promise.all(doc.layers.map(async layer=>{if(!layer.bitmap)return;const img=new Image();img.src=layer.bitmap;await img.decode();bufferFor(layer).getContext("2d")!.drawImage(img,0,0,px.width,px.height)}));renderDocument();}
  function resizeBuffers(width:number,height:number){for(const [id,old] of layerBuffers){const next=document.createElement("canvas");next.width=width;next.height=height;next.getContext("2d")!.drawImage(old,0,0,width,height);layerBuffers.set(id,next)}}
  function renderedLayer(layer:ArtLayer){const source=bufferFor(layer),out=blankBuffer(),ctx=out.getContext("2d")!;let processed:HTMLCanvasElement=source;const pixelEffects=layer.effects.filter(e=>e.enabled&&!["array","blur","shadow","stroke"].includes(e.type));if(pixelEffects.length){processed=blankBuffer();processed.getContext("2d")!.putImageData(processPixels(source.getContext("2d")!.getImageData(0,0,source.width,source.height),pixelEffects),0,0)}const blur=layer.effects.find(e=>e.enabled&&e.type==="blur"),shadow=layer.effects.find(e=>e.enabled&&e.type==="shadow");if(blur)ctx.filter=`blur(${Number(blur.params.radius)}px)`;if(shadow){ctx.shadowOffsetX=Number(shadow.params.x);ctx.shadowOffsetY=Number(shadow.params.y);ctx.shadowBlur=Number(shadow.params.blur);ctx.shadowColor=String(shadow.params.color)}ctx.drawImage(processed,0,0);ctx.filter="none";ctx.shadowColor="transparent";for(const effect of layer.effects.filter(e=>e.enabled&&e.type==="array")){const current=blankBuffer();current.getContext("2d")!.drawImage(out,0,0);for(let i=1;i<Number(effect.params.count);i++)ctx.drawImage(current,Number(effect.params.dx)*i,Number(effect.params.dy)*i)}return out;}
  function renderDocument(){if(!canvas)return;if(canvas.width!==px.width||canvas.height!==px.height){canvas.width=px.width;canvas.height=px.height}const c=canvas.getContext("2d")!;c.clearRect(0,0,canvas.width,canvas.height);if(doc.background){c.fillStyle=doc.background;c.fillRect(0,0,canvas.width,canvas.height)}for(const layer of [...doc.layers].reverse()){if(!layer.visible)continue;c.save();c.globalAlpha=layer.opacity;c.globalCompositeOperation=layer.blendMode as GlobalCompositeOperation;c.drawImage(renderedLayer(layer),0,0);c.restore()}}
  function setupCanvas(){if(!canvas)return;const changed=canvas.width!==px.width||canvas.height!==px.height;if(changed&&canvas.width)resizeBuffers(px.width,px.height);canvas.width=px.width;canvas.height=px.height;renderDocument();}
  function point(e:PointerEvent){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height};}
  function checkpoint(){if(!active)return;history=[...history.slice(-39),bufferFor(active).toDataURL()];future=[];}
  function sampleColor(p:{x:number;y:number}){const d=canvas.getContext("2d")!.getImageData(Math.floor(p.x),Math.floor(p.y),1,1).data;color=`#${[d[0],d[1],d[2]].map(v=>v.toString(16).padStart(2,"0")).join("")}`;}
  function pointerDown(e:PointerEvent){if(e.button===1){e.preventDefault();panning=true;panStart={x:e.clientX,y:e.clientY,left:stage.scrollLeft,top:stage.scrollTop};canvas.setPointerCapture(e.pointerId);return}const p=point(e);if((e.altKey&&e.button===0)||tool==="eyedropper"){sampleColor(p);return}if(e.button!==0||!active||active.locked||tool==="select")return;checkpoint();drawing=true;start=p;const c=bufferFor(active).getContext("2d")!;snapshot=c.getImageData(0,0,c.canvas.width,c.canvas.height);canvas.setPointerCapture(e.pointerId);if(tool==="fill"){c.fillStyle=color;c.fillRect(0,0,c.canvas.width,c.canvas.height);drawing=false;commit();}}
  function pointerMove(e:PointerEvent){const p=point(e);cursor={x:p.x,y:p.y,visible:true};if(panning){stage.scrollLeft=panStart.left-(e.clientX-panStart.x);stage.scrollTop=panStart.top-(e.clientY-panStart.y);return}if(!drawing||!active)return;const c=bufferFor(active).getContext("2d")!;c.lineCap="round";c.lineJoin="round";c.lineWidth=size;c.strokeStyle=color;c.fillStyle=color;if(tool==="brush"||tool==="eraser"){c.globalCompositeOperation=tool==="eraser"?"destination-out":"source-over";c.beginPath();c.moveTo(start.x,start.y);c.lineTo(p.x,p.y);c.stroke();start=p}else if(snapshot){c.putImageData(snapshot,0,0);c.beginPath();if(tool==="line"){c.moveTo(start.x,start.y);c.lineTo(p.x,p.y)}if(tool==="rect")c.rect(start.x,start.y,p.x-start.x,p.y-start.y);if(tool==="ellipse")c.ellipse((start.x+p.x)/2,(start.y+p.y)/2,Math.abs(p.x-start.x)/2,Math.abs(p.y-start.y)/2,0,0,Math.PI*2);c.stroke()}c.globalCompositeOperation="source-over";renderDocument();}
  function pointerUp(){if(panning){panning=false;return}if(!drawing)return;drawing=false;commit();}
  function commit(){if(active){active.bitmap=bufferFor(active).toDataURL("image/png");doc={...doc,updatedAt:new Date().toISOString(),layers:[...doc.layers]};renderDocument();queueSave();}}
  async function restoreDataUrl(value:string){if(!active)return;const img=new Image();img.src=value;await img.decode();const c=bufferFor(active).getContext("2d")!;c.clearRect(0,0,c.canvas.width,c.canvas.height);c.drawImage(img,0,0);renderDocument();}
  async function undo(){const value=history.pop();if(!value||!active)return;future=[bufferFor(active).toDataURL(),...future];history=[...history];await restoreDataUrl(value);commit();}
  async function redo(){const value=future.shift();if(!value||!active)return;history=[...history,bufferFor(active).toDataURL()];future=[...future];await restoreDataUrl(value);commit();}
  let timer:number; function queueSave(){clearTimeout(timer);timer=window.setTimeout(async()=>{await saveAutosave(doc,assets);status=t("saved");setTimeout(()=>status="",1200)},600);}
  function addLayer(){const layer=newLayer(locale==="zh-CN"?`图层 ${doc.layers.length+1}`:`Layer ${doc.layers.length+1}`);doc={...doc,layers:[layer,...doc.layers],activeLayerId:layer.id};bufferFor(layer);renderDocument();queueSave();}
  function addText(){const layer=newLayer(locale==="zh-CN"?"文字":"Text");layer.type="text";layer.text=locale==="zh-CN"?"双击编辑文字":"Double-click to edit";layer.font="sans-serif";layer.fontSize=64;layer.color=color;doc={...doc,layers:[layer,...doc.layers],activeLayerId:layer.id};const c=bufferFor(layer).getContext("2d")!;c.font=`${layer.fontSize}px ${layer.font}`;c.fillStyle=color;c.fillText(layer.text,px.trimX+30,px.trimY+90);commit();}
  function duplicateLayer(){if(!active)return;const copy=structuredClone(active);copy.id=uid();copy.name+=locale==="zh-CN"?" 副本":" copy";const buffer=blankBuffer();buffer.getContext("2d")!.drawImage(bufferFor(active),0,0);layerBuffers.set(copy.id,buffer);copy.bitmap=buffer.toDataURL();doc={...doc,layers:[copy,...doc.layers],activeLayerId:copy.id};renderDocument();queueSave();}
  function removeLayer(){if(!active)return;layerBuffers.delete(active.id);const layers=doc.layers.filter(l=>l.id!==active.id);doc={...doc,layers,activeLayerId:layers[0]?.id};renderDocument();queueSave();}
  function moveLayer(index:number,delta:number){const target=index+delta;if(target<0||target>=doc.layers.length)return;const layers=[...doc.layers];[layers[index],layers[target]]=[layers[target],layers[index]];doc={...doc,layers};renderDocument();queueSave();}
  function selectLayer(id:string){doc={...doc,activeLayerId:id};}
  function toggleLayer(layer:ArtLayer){layer.visible=!layer.visible;doc={...doc,layers:[...doc.layers]};renderDocument();queueSave();}
  function setBleed(side:keyof typeof doc.spec.bleed,event:Event){doc.spec.bleed[side]=Number((event.target as HTMLInputElement).value);updateSpec();}
  function setEffectParam(effect:NonNullable<typeof active>["effects"][number],key:string,event:Event){const input=event.target as HTMLInputElement;effect.params[key]=input.type==="checkbox"?input.checked:input.type==="number"?Number(input.value):input.value;applyEffects();}
  function openSettings(){settingsOriginal=structuredClone(doc.spec);showSettings=true;}
  async function cancelSettings(){if(settingsOriginal)doc={...doc,spec:settingsOriginal};showSettings=false;await tick();setupCanvas();}
  async function importImage(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;const bitmap=await createImageBitmap(file);const bytes=await file.arrayBuffer(),hash=await crypto.subtle.digest("SHA-256",bytes),id=uid();const checksum=[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join("");assets.set(id,{id,name:file.name,mime:file.type,width:bitmap.width,height:bitmap.height,checksum,bytes:file});const layer=newLayer(file.name);layer.type="image";layer.assetId=id;doc={...doc,layers:[layer,...doc.layers],activeLayerId:layer.id};const scale=Math.min(px.width/bitmap.width,px.height/bitmap.height,.9),b=bufferFor(layer);b.getContext("2d")!.drawImage(bitmap,(px.width-bitmap.width*scale)/2,(px.height-bitmap.height*scale)/2,bitmap.width*scale,bitmap.height*scale);layer.bitmap=b.toDataURL();commit();}
  function addEffect(type:EffectType){if(!active)return;active.effects=[...active.effects,createEffect(type)];doc={...doc,layers:[...doc.layers]};applyEffects();}
  async function applyEffects(){renderDocument();queueSave();}
  function moveEffect(index:number,delta:number){if(!active)return;const n=index+delta;if(n<0||n>=active.effects.length)return;[active.effects[index],active.effects[n]]=[active.effects[n],active.effects[index]];active.effects=[...active.effects];doc={...doc,layers:[...doc.layers]};applyEffects();}
  function removeEffect(index:number){if(!active)return;active.effects=active.effects.filter((_,i)=>i!==index);doc={...doc,layers:[...doc.layers]};applyEffects();}
  function toggleTheme(){const root=document.documentElement,next=root.dataset.theme==="xianii"?"xianii-light":"xianii";root.dataset.theme=next;localStorage.setItem("theme",next);}
  function toggleLocale(){locale=locale==="zh-CN"?"en":"zh-CN";doc={...doc,locale};localStorage.setItem("locale",locale);}
  function fresh(){doc=newDocument(locale);assets=new Map();layerBuffers.clear();history=[];future=[];setTimeout(setupCanvas);queueSave();}
  async function saveFile(){download(await exportProject(doc,assets),`${doc.name||"Untitled"}.artmaker`);}
  async function openProject(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;const loaded=await importProject(file);doc=loaded.document;assets=new Map(loaded.assets.map(a=>[a.id,a]));locale=doc.locale;await tick();setupCanvas();await hydrateLayers();queueSave();}
  async function exportPng(){renderDocument();const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(v=>v?resolve(v):reject(),"image/png"));download(blob,`${doc.name||"ArtMaker"}-${px.width}x${px.height}.png`);}
  async function updateSpec(){doc={...doc,spec:{...doc.spec,bleed:{...doc.spec.bleed}}};await tick();setupCanvas();queueSave();}
  const zoomLevels=[.25,.5,1,2,3,4];
  async function setZoom(next:number,clientX?:number,clientY?:number){const old=zoom,rect=stage.getBoundingClientRect(),x=clientX??rect.left+rect.width/2,y=clientY??rect.top+rect.height/2,docX=(stage.scrollLeft+x-rect.left)/old,docY=(stage.scrollTop+y-rect.top)/old;zoom=next;await tick();stage.scrollLeft=docX*zoom-(x-rect.left);stage.scrollTop=docY*zoom-(y-rect.top);}
  function wheel(e:WheelEvent){e.preventDefault();if(e.shiftKey){size=Math.max(1,Math.min(500,size+(e.deltaY<0?1:-1)));return}const index=zoomLevels.indexOf(zoom),next=zoomLevels[Math.max(0,Math.min(zoomLevels.length-1,index+(e.deltaY<0?1:-1)))];if(next!==zoom)setZoom(next,e.clientX,e.clientY);}
  onMount(async()=>{locale=(localStorage.getItem("locale") as typeof locale)||((navigator.language.startsWith("zh"))?"zh-CN":"en");const saved=await loadAutosave();if(saved){doc=saved.document;assets=new Map(saved.assets.map(a=>[a.id,a]));locale=doc.locale;status=t("restore");}setupCanvas();await hydrateLayers();});
</script>

<svelte:window onkeydown={(e)=>{if((e.ctrlKey||e.metaKey)&&e.key==="z"){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key==="s"){e.preventDefault();saveFile()}}}/>
<div class="app-shell">
  <header class="topbar">
    <div class="brand"><span class="brand-mark">A</span><div><strong>ArtMaker</strong><small>PRINT CANVAS</small></div></div>
    <nav class="menu-actions"><button onclick={fresh}>{t("new")}</button><button onclick={()=>projectInput.click()}>{t("open")}</button><button onclick={saveFile}>{t("save")}</button><span></span><button onclick={undo} disabled={!history.length}>{t("undo")}</button><button onclick={redo} disabled={!future.length}>{t("redo")}</button></nav>
    <div class="header-end"><span class="autosave">{status||`${doc.spec.dpi} DPI · ${px.width} × ${px.height} px`}</span><button class="icon-btn" onclick={toggleTheme} title={t("theme")}>◐</button><button class="lang-btn" onclick={toggleLocale}>{t("lang")}</button><button class="export-btn" onclick={exportPng}>{t("export")}</button></div>
  </header>
  <div class="workspace">
    <aside class="toolrail">
      {#each tools as item}<button class:active={tool===item.id} onclick={()=>tool=item.id} title={locale==="zh-CN"?item.zh:item.en}><b>{item.icon}</b><small>{locale==="zh-CN"?item.zh:item.en}</small></button>{/each}
    </aside>
    <section class="center">
      <div class="contextbar"><label><span>{locale==="zh-CN"?"颜色":"Color"}</span><input type="color" bind:value={color}/></label><label><span>{locale==="zh-CN"?"尺寸":"Size"}</span><input class="range" type="range" min="1" max="500" bind:value={size}/><output>{size}px</output></label><button onclick={()=>fileInput.click()}>＋ {t("import")}</button><button onclick={openSettings}>⚙ {t("settings")}</button></div>
      <div class="canvas-stage" class:panning bind:this={stage} onwheel={wheel}><div class="ruler top">0　　　　25　　　　50　　　　75　　　　100</div><div class="ruler left">0<br/><br/>25<br/><br/>50</div><div class="canvas-wrap" style={canvasStyle}><canvas class:pixelated={zoom>=1&&Number.isInteger(zoom)} bind:this={canvas} onpointerdown={pointerDown} onpointermove={pointerMove} onpointerup={pointerUp} onpointercancel={pointerUp} onpointerleave={()=>cursor.visible=false}></canvas><div class="trim-guide" style={`left:${px.trimX*zoom}px;top:${px.trimY*zoom}px;width:${px.trimWidth*zoom}px;height:${px.trimHeight*zoom}px`}></div><div class="safe-guide" style={`left:${(px.trimX+safePx)*zoom}px;top:${(px.trimY+safePx)*zoom}px;width:${(px.trimWidth-safePx*2)*zoom}px;height:${(px.trimHeight-safePx*2)*zoom}px`}></div>{#if cursor.visible&&(tool==="brush"||tool==="eraser")}<div class="brush-cursor" style={`left:${cursor.x*zoom}px;top:${cursor.y*zoom}px;width:${Math.max(1,size*zoom)}px;height:${Math.max(1,size*zoom)}px`}></div>{/if}<div class="trim-label">TRIM / 成品</div></div><div class="zoom"><button onclick={()=>setZoom(zoomLevels[Math.max(0,zoomLevels.indexOf(zoom)-1)])}>−</button><span>{Math.round(zoom*100)}%</span><button onclick={()=>setZoom(zoomLevels[Math.min(zoomLevels.length-1,zoomLevels.indexOf(zoom)+1)])}>＋</button></div></div>
    </section>
    <aside class="rightbar">
      <section class="panel layer-panel"><div class="panel-title"><b>{t("layers")}</b><div><button onclick={addText}>T</button><button onclick={addLayer}>＋</button></div></div><div class="layer-list">{#each doc.layers as layer,index (layer.id)}<button class="layer-item" class:selected={layer.id===doc.activeLayerId} onclick={()=>selectLayer(layer.id)}><span class="eye" onclick={(e)=>{e.stopPropagation();toggleLayer(layer)}}>{layer.visible?"●":"○"}</span><span class="thumb">{layer.type==="image"?"▧":layer.type==="text"?"T":"✦"}</span><span class="layer-name">{layer.name}<small>{layer.type.toUpperCase()} · {Math.round(layer.opacity*100)}%</small></span><span class="layer-move"><i onclick={(e)=>{e.stopPropagation();moveLayer(index,-1)}}>↑</i><i onclick={(e)=>{e.stopPropagation();moveLayer(index,1)}}>↓</i></span></button>{/each}</div>{#if active}<div class="layer-props"><label>{t("opacity")} <input type="range" min="0" max="1" step=".01" bind:value={active.opacity} oninput={()=>{renderDocument();queueSave()}}/></label><label>{t("blend")} <select bind:value={active.blendMode} onchange={()=>{renderDocument();queueSave()}}><option value="normal">Normal</option><option value="multiply">Multiply</option><option value="screen">Screen</option><option value="overlay">Overlay</option></select></label><div><button onclick={duplicateLayer}>{t("duplicate")}</button><button class="danger" onclick={removeLayer}>{t("remove")}</button></div></div>{/if}</section>
      <section class="panel effects-panel"><div class="panel-title"><b>{t("effects")}</b><button onclick={()=>showEffects=!showEffects}>＋</button></div>{#if showEffects}<div class="effect-picker">{#each effectRegistry as effect}<button onclick={()=>{addEffect(effect.type);showEffects=false}}>{effect.label[locale]}</button>{/each}</div>{/if}{#if active?.effects.length}<div class="effect-list">{#each active.effects as effect,index (effect.id)}<div class="effect-item"><div><input type="checkbox" bind:checked={effect.enabled} onchange={applyEffects}/><b>{effectRegistry.find(x=>x.type===effect.type)?.label[locale]}</b><span><button onclick={()=>moveEffect(index,-1)}>↑</button><button onclick={()=>moveEffect(index,1)}>↓</button><button onclick={()=>removeEffect(index)}>×</button></span></div>{#each Object.entries(effect.params).slice(0,4) as [key,value]}<label>{key}{#if typeof value==="boolean"}<input type="checkbox" checked={Boolean(value)} onchange={(e)=>setEffectParam(effect,key,e)}/>{:else if String(key).includes("color")||key==="from"||key==="to"}<input type="color" value={String(value)} onchange={(e)=>setEffectParam(effect,key,e)}/>{:else}<input type="number" value={Number(value)} onchange={(e)=>setEffectParam(effect,key,e)}/>{/if}</label>{/each}</div>{/each}</div>{:else}<p class="empty-effects">{t("empty")}</p>{/if}</section>
    </aside>
  </div>
</div>
{#if showSettings}<div class="modal-backdrop" role="presentation" onclick={(e)=>{if(e.target===e.currentTarget)cancelSettings()}}><section class="settings-modal" role="dialog" aria-modal="true" aria-label={t("settings")}><div class="panel-title"><b>{t("settings")}</b><button onclick={cancelSettings}>×</button></div><div class="field-grid"><label>{t("width")}<input type="number" bind:value={doc.spec.width}/></label><label>{t("height")}<input type="number" bind:value={doc.spec.height}/></label><label>{t("dpi")}<input type="number" min="72" max="2400" bind:value={doc.spec.dpi}/></label><label>{locale==="zh-CN"?"单位":"Unit"}<select bind:value={doc.spec.unit}><option value="mm">mm</option><option value="inch">inch</option></select></label></div><label class="wide-field">{t("bleed")}<div class="bleed-row">{#each ["top","right","bottom","left"] as side}<input aria-label={side} type="number" value={doc.spec.bleed[side as keyof typeof doc.spec.bleed]} onchange={(e)=>{doc.spec.bleed[side as keyof typeof doc.spec.bleed]=Number(e.currentTarget.value);doc={...doc}}}/>{/each}</div></label><label class="wide-field">{t("safe")}<input type="number" bind:value={doc.spec.safeMargin}/></label><div class="pixel-card"><small>{t("pixel")}</small><strong>{px.width.toLocaleString()} × {px.height.toLocaleString()} px</strong><span>≈ {Math.round(px.width*px.height*4/1024/1024)} MB RGBA</span></div><footer><button onclick={cancelSettings}>{locale==="zh-CN"?"取消":"Cancel"}</button><button class="apply" onclick={async()=>{await updateSpec();settingsOriginal=null;showSettings=false}}>{locale==="zh-CN"?"应用":"Apply"}</button></footer></section></div>{/if}
<input class="hidden" bind:this={fileInput} type="file" accept="image/png,image/jpeg,image/webp" onchange={importImage}/><input class="hidden" bind:this={projectInput} type="file" accept=".artmaker" onchange={openProject}/>
